#pragma once

#define MAX_PASSWORD_LEGNTH	32
#define MAX_ACCOUNT_LEGNTH  32

#define MAX_NAME_LEN	32
#define MAX_IP_CHAR_LEN  32

#define SUCCESS   0

#define MAX_SOCKET_BUFF_SIZE  64000
#define MAX_SOCKET_BUFF_LENGTH  (MAX_SOCKET_BUFF_SIZE * 2 + 1)

#define MAX_ONCE_MSG_LEGNTH	5