//连接错误
enum emConError
{
	EMCONERROR_WIN_SOCKET_INIT = -100, //winsocket环境初始化失败	
	EMCONERROR_HASCONNECT = -101, //已连接
	EMCONERROR_HAS_LOAD_CONINFO = -102, //已加载
	EMCONERROR_SERVER_NOT_OPEN = -103, //未打开文件
	EMCONERROR_SERVERFILE_IS_NULL = -104, //文件内容为空
	EMCONERROR_SERVER_INDEX_IS_NULL = -105, //测试的索引为空
	EMCONERROR_SERVER_DATA_IS_NULL = -106, //所选中的服务器数据为NULL
	EMCONERROR_SERVER_DATA_NOT_FULL = -107, //所选中的服务器数据不全
	EMCONERROR_SOCKET_CREATE = -108, //创建的socket错误
	EMCONERROR_NET_NOT_CON = -109, //网络未连接
	EMCONERROR_CONTEXT_IS_NULL = -110, //接收消息内容的缓存为空
	EMCONERROR_CONNECT_USER_MAX = -111, //连接的用户数量达到最大
};

enum emMessageQueueError
{
	ERROR_PUSH_MESSAGE_QUEUE_FULL = -200, //push时，队列已满
	ERROR_POP_MESSAGE_QUEUE_FULL = -201, //pop时，队列为空
	ERROR_SELECT_MESSAGE_HADNLE = -202,//select处理消息时候，出错
	ERROR_MESSAGE_USE_INDEX = -203, //消息，用户索引非法
};

enum emLoginSceneError
{
	ERROR_LOGIN_SCENE_NOT_CONNECT    = -300, //未连接或已登陆
	ERROR_LOGIN_SCENE_ACOUNT_INVAILD = -301, //账号或密码错误
	ERROR_LOGIN_SCENE_ROLEID_ZERO    = -302, //加载的RoleID为0
	ERROR_LOGIN_SCENE_ROLEDATA_NULL	 = -303, //加载的Role数据为NULL
	ERROR_LOGIN_SCENE_ROLEDATA_RESULT  = -304, //加载的Role数据结果出错
	ERROR_LOGIN_SCENE_ROLEDATA_INVALLD = -305, //加载的Role数据不对出错
	ERROR_LOGIN_SCENE_ROLEDATA_FECTH   = -306, //加载的Role数据出错
};

enum emCreateAccountError
{
	ERROR_CREATE_ACCOUNT_EXIST		 = -400, //账号已存在
	ERROR_CREATE_ACCOUNT_ACCOUNT	 = -401, //创建账号出错
	ERROR_CREATE_ACCOUNT_ROLE		 = -402, //创建玩家数据出错

};